name: Análise de Segurança com GitHub CodeQL

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  codeql-analysis:
    name: Scan com CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Permissão para escrever na aba "Security"
      actions: read
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 1: Inicializa o CodeQL
      # Ele prepara o ambiente e detecta a linguagem (Python, no nosso caso)
      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python # Especificamos a linguagem do nosso projeto

      # Passo 2: Roda a análise do CodeQL
      # Ele "constrói" um banco de dados do seu código e executa as queries de segurança
      - name: Executar análise do CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"