name: Análise de Segurança Estática (SAST)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Scan SAST com Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Semgrep
        # AJUSTE: Trocamos @v2 por uma versão específica para evitar problemas de resolução.
        uses: semgrep/semgrep-action@v2.2.0 
        with:
          output-format: sarif
          output-file: semgrep.sarif

      - name: Upload do relatório SARIF como artefato
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-sast-semgrep
          path: semgrep.sarif
          retention-days: 7

      - name: Upload SARIF para a aba de Segurança do GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep