name: Pipeline de Segurança (SAST e DAST)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  # JOB 1: ANÁLISE ESTÁTICA (SAST)
  codeql-analysis:
    name: Scan SAST com CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Executar análise do CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"

  # JOB 2: ANÁLISE DINÂMICA (DAST)
  dast-zap-scan:
    name: Scan DAST com OWASP ZAP
    runs-on: ubuntu-latest
    needs: codeql-analysis 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências do projeto
        run: pip install -r requirements.txt

      - name: Iniciar aplicação Flask em background
        run: |
          echo "Iniciando servidor Flask na porta 5000..."
          python app.py &
          echo "Aguardando 10 segundos para o servidor iniciar completamente..."
          sleep 10

      # ---- PASSO NOVO ADICIONADO AQUI ----
      - name: Dar permissão de escrita para o ZAP
        # O container do ZAP roda com um usuário diferente (não-root)
        # e precisa de permissão explícita para escrever o relatório na pasta de trabalho.
        run: |
          chmod -R 777 .

      - name: Executar OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:5000'
          # Simplifiquei os cmd_options para gerar apenas o relatório que precisamos
          cmd_options: '-r dast-report.html'

      - name: Upload do Relatório DAST (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-dast-zap
          path: dast-report.html
          retention-days: 7